name: build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  sast_scan:
    name: Run SAST Scan
  image_scan:
     name: Build Image and Run Image Scan
     runs-on: ubuntu-latest

     steps:
     - name: Checkout code
       uses: actions/checkout@v4
  
     - name: Set up Docker
       uses: docker-practice/actions-setup-docker@v1
       with:
        docker_version: '20.10.7'
  
     - name: Build Docker Image
       run: docker build -f Dockerfile -t pygoat_app:latest .
      
     - name: Docker Scout Scan
       uses: docker/scout-action@v1.15.0
       with:
         dockerhub-user: ${{ yuchichen1002 }}
         dockerhub-password: ${{ dckr_pat_WANucQU3u23-WRgqcmKmFr9rFSA }}
         command: quickview,cves
         only-severities: critical,high
         sarif-file: scout-report.sarif
  
     - name: Upload Artifact
       uses: actions/upload-artifact@v3
       if: always()
       with:
         name: docker-scout-findings
         path: scout-report.sarif
